const ApiConstants = {
  Trending: "/trending-comics",
  Genres: "/genres",
  ComicsByGenre: "/genres",
  Search: "/search",
  SearchSuggest: "/search-suggest",
  RecommendComics: "/recommend-comics",
  NewComics: "/new-comics",
  BoyComics: "/boy-comics",
  GirlComics: "/girl-comics",
  CompletedComics: "/completed-comics",
  RecentUpdateComics: "/recent-update-comics",
  ComicDetail: "/comics",
  ComicChapters: "/comics",
  ComicSingleChapter: "/comics",
  TopAllComic: "/top",
  TopDaily: "/top/daily",
  TopWeekly: "/top/weekly",
  TopMonthly: "/top/monthly",
  TopChapter: "/top/chapter",
  TopFollow: "/top/follow",
  TopComment: "/top/comment",
};

export default ApiConstants;
